version: '3'

services:
  postgres_shopping_cart:
    image: postgres:10
    container_name: db_shopping_cart
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "shopping_cart"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
