version: '3'

services:
  postgres_shopping_cart:
    image: postgres:10
    container_name: db_shopping_cart
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "shopping_cart"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  nestjs:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 4000:4000
    container_name: nestjs
    depends_on:
      - postgres_shopping_cart
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules

  nextjs:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    container_name: nextjs
    depends_on:
      - postgres_shopping_cart
    volumes:
      - ./web:/usr/src/app/web
      - /usr/src/app/web/node_modules

